# Generated by Django 2.0.2 on 2018-02-02 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_Name', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, max_length=200)),
                ('date_of_Birth', models.IntegerField(blank=True, max_length=200)),
                ('home_Address', models.CharField(blank=True, max_length=200)),
                ('phone_Number', models.IntegerField(blank=True, max_length=200)),
                ('next_of_kin', models.CharField(blank=True, max_length=200)),
                ('email_Address', models.EmailField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
