# Generated by Django 2.0.2 on 2018-02-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_Birth',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_Number',
            field=models.IntegerField(blank=True),
        ),
    ]
