# Generated by Django 2.0.2 on 2018-02-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Care', '0002_auto_20180202_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_Birth',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_Number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
